### ISSUE TITLE
Issue with ArcGIS 10.7 and Pro 2.9 LiDAR Tools

### ISSUE THREAD

**Issue by JackC4899** [giswqs/WhiteboxTools-ArcGIS#29] opened 2021-12-06 21:41 UTC
Hi, I have a WTB toolbox download from over a year ago (has fewer tools than the new download, like 'LidarContour') that works okay on my personal computer. However, I just downloaded a fresh toolbox to my Amazon EC2 ArcGIS Server instance, and tried to utilize the 'LidarContour' and 'LasToShapefile' in both ArcMap and Pro, and both instantaneously fail and show the same errors in the GP results 'messages' window. Tool inputs and error messages are show below. Something with an unexpected _keyword_ argument.

LiDAR Data: .LAS file downloaded from USGS 3DEP.

**Error Messages/ Tool Inputs**
![Las2Shp_Failure](https://user-images.githubusercontent.com/17255699/144928469-b81c4fc2-0487-449d-a755-f569beabf538.PNG)
![LidarContour_Failure](https://user-images.githubusercontent.com/17255699/144928491-f8b9b45e-bcaa-4134-a733-c26d1cc1572e.PNG)

**Comment by jblindsay** [comment] 2021-12-07 11:57
The LidarContour tool is part of the WhiteboxTools LiDAR and Remote Sensing Extension. Running this tool requires a valid license. For more information, see the [WhiteboxTools website](https://www.whiteboxgeo.com/lidar-and-rs-extension/).

**Comment by giswqs** [comment] 2021-12-07 18:47
It appears that the issue was caused by the inconsistent parameter names, i.e., `input` and `i`. The ArcGIS frontend was built upon the json file containing all the tool parameters. The parameter name for `LasToShapefile` in the json file is `input` (the one ArcGIS is using), while in `whitebox_tools.py` the parameter name is `i`. Behind the scene, the ArcGIS frontend calls `wbt.las_to_shapefile`. The `input` parameter is not recognized by `wbt.las_to_shapefile`, and that's why it throws the error. I guess there might be other tools being affected by this. I will look into it and find a way to correct them automatically. 

https://raw.githubusercontent.com/giswqs/whiteboxgui/master/whiteboxgui/data/whitebox_tools.json
![image](https://user-images.githubusercontent.com/5016453/145086329-d12c87cc-1a48-490e-bcaf-880354d298ee.png)

https://raw.githubusercontent.com/giswqs/WhiteboxTools-ArcGIS/master/WBT/PRE/WhiteboxTools.py
![image](https://user-images.githubusercontent.com/5016453/145086587-6ee07f37-71f3-4cdc-8d3a-c3698e9b6a29.png)

https://github.com/giswqs/WhiteboxTools-ArcGIS/blob/master/WBT/whitebox_tools.py#L6408
![image](https://user-images.githubusercontent.com/5016453/145086706-62917080-982b-49e9-bd9e-7df801d3bbda.png)

**Comment by jblindsay** [comment] 2021-12-07 18:50
In the WBT backend, parameters can have multiple names (e.g. '--input' or '-i'). For the Python API, I also select the longest parameter name, since they are more descriptive. The one exception is for a parameter named 'input', which is quite common in WBT tools. 'input' is a key word in Python and therefore I cannot use it as a parameter name and always default to 'i' instead.

**Comment by giswqs** [comment] 2021-12-07 19:06
@jblindsay Thanks for clarifying. I was able to fix it. 

@JackC4899 Please download the latest version and try again. 
https://github.com/giswqs/WhiteboxTools-ArcGIS/archive/refs/heads/master.zip

**Comment by JackC4899** [comment] 2021-12-07 19:09
@jblindsay and @giswqs  thanks for your quick replies. I ended up realizing that about the LidarContour tool very soon after posting this, but figured I'd keep the snip about it's keyword error in here.

I appreciate the super-speedy fixes! I'll go ahead and download the toolbox again. Happy Holidays!

**Comment by giswqs** [comment] 2021-12-08 14:22
@JackC4899 I am closing this issue. Feel free to reopen if you are still experiencing issues.

**Closed by giswqs** 2021-12-08 14:22 UTC
