### ISSUE TITLE
Failed with ArcMap 10.6

### ISSUE THREAD

**Issue by ysynoya** [giswqs/WhiteboxTools-ArcGIS#9] opened 2020-01-12 06:04 UTC
![Capture2](https://user-images.githubusercontent.com/46764762/72214795-2ef3cf80-3544-11ea-9307-70e2304f66e9.PNG)
I wonder why can't I import the toolbox =(

**Comment by giswqs** [comment] 2020-01-12 15:50
It works fine on my ArcMap 10.7. Could you right-click the toolbox and select **Check Syntax**  to see what error messages you get?

![](https://i.imgur.com/y1HNYlv.png)

**Comment by ysynoya** [comment] 2020-01-13 02:48
THX for your reply! I checked and think it might be my anaconda2 environment. I also have anaconda3, but I don't know how to switch to that environment. (Most of the time I need a python2 environment to use arcpy since I don't have a pro version) 
![Capture3](https://user-images.githubusercontent.com/46764762/72230620-ac294e00-35f1-11ea-81a8-898d711208d1.PNG)

**Comment by giswqs** [comment] 2020-01-13 03:38
The error was probably caused by your default Python interpreter, which is your Anaconda2. In order to run WhiteboxTools-ArcGIS, you should use the Python interpreter installed by ArcGIS (`C:\Python27`). Follow the instructions below to switch your default Python interpreter from Anaconda to ArcGIS:

- Go to This PC -> Right-click -> Click on Properties -> Advanced System Settings.
- You will see the System Properties. From here navigate to the "Advanced" Tab -> Click on Environment Variables.
- You will see a top half for the user variables and the bottom half for System variables.
- Check the System Variables and double-click on the Path(to edit the Path).
- Check for the path of Python(i.e., C:\Python27) and move it to the top of the Path list. 
- See the screenshot below

![](https://i.imgur.com/KlIfQJs.png)

**Comment by giswqs** [comment] 2020-01-27 21:32
@ysynoya Have you resolved the issue? I am closing this issue for now. Feel free to reopen the issue if needed.

**Closed by giswqs** 2020-01-27 21:32 UTC

**Comment by YUHAN-G** [comment] 2020-03-12 00:57
I have tried to change Arcgis10.6 python 2.7 on top, but It was still not working.

**Comment by giswqs** [comment] 2020-03-12 02:17
@YUHAN-G What error message did you get?
